repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-added-large-files
  -   repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.0
      hooks:
        - id: go-fmt
        - id: go-imports
        - id: golangci-lint
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.13.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
